mq:
  username: bztgnhov
  password: ${MQ_PASSWORD}
logging:
  file:
    name: logs/PermitBackup.log
spring:
  config:
    import: optional:file:.env.local[.properties]
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: jdbc:postgresql://localhost:5431/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/liquibase-changelog.xml
permit:
  password: ${PERMIT_PASSWORD}
  username: Admin
server:
  port: '8080'
saveFolder:
  ${SAVE_PATH}
